name: 'md-check-links'
description: 'Check if links are valid in markdown files.'
author: 'Maintainers'
branding:
  icon: 'link'  
  color: 'green'
inputs:
  quiet:
    description: 'Use yes to enable markdown-link-check quiet mode which only lists errors.'
    required: true
    default: 'no'
  verbose:
    description: 'Use yes to enable markdown-link-check verbose mode which lists additional details.'
    required: true
    default: 'no'
  config:
    description: 'Specify path to a markdown-link-check JSON configuration file.'
    required: true
    default: 'mlc_config.json'
  directory:
    description: 'Specify path to a custom folder where your markdown files are located.'
    required: true
    default: '.'
  depth:
    description: 'Specify a depth of directories you want to search for markdown files.'
    required: true
    default: '-1'
  modified:
    description: 'Use yes to only check for modified markdown files instead of checking all markdown files.'
    required: true
    default: 'no'
  branch:
    description: 'Use this to specify the base branch against which the action finds the modified files.'
    required: true
    default: 'main'
  prefix:
    description: 'Prefix of files to check.'
    required: true
    default: ''
  extension:
    description: 'Use this to specify the file extension of Markdown files.'
    required: true
    default: '.md'
  file:
    description: 'Specify additional files you want to check'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.quiet }}
    - ${{ inputs.verbose }}
    - ${{ inputs.config }}
    - ${{ inputs.directory }}
    - ${{ inputs.depth }}
    - ${{ inputs.modified }}
    - ${{ inputs.branch }}
    - ${{ inputs.prefix }}
    - ${{ inputs.extension }}
    - ${{ inputs.file }}
